SHOW TABLES;
CREATE DATABASE coffee_shop;
USE coffee_shop;

CREATE TABLE PRODUCTS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30),
    price DECIMAL(3,2),
    coffee_orign varchar(20)
);

CREATE TABLE CUSTOMERS(
    ID INT,
    FIRST_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30),
    GENDER ENUM('M','F'),
    PHONE_NUMBER INT(10)
);
--CREATE TABLE ORDERS(
--ID INT AUTO_INCREMENT PRIMARY KEY,
--PRODUCT_ID INT,
--CUSTOMER_ID INT,
--FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID),
--FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);
show tables;
select * from ORDERS;
show tables;
describe CUSTOMERS;
ALTER TABLE CUSTOMERS
ADD PRIMARY KEY(PHONE_NUMBER) ;
ALTER TABLE CUSTOMERS
DROP PRIMARY KEY ;
ALTER TABLE CUSTOMERS CHANGE COLUMN `PHONE_NUMBER` `CONTACT_NUMBER` INT(10);



